language: node_js
node_js:
  - "node"
install:
  - npm install hexo-cli -g
script:
  - hexo generate
cache: npm
deploy:
  provider: pages
  local_dir: public/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  keep_history: true
  fqdn: "hexo.tv"
  on:
    branch: master